### ISSUE TITLE
Cursor jumps to other monitor when hovering an overlayed window

### ISSUE THREAD

**Issue by Sirush** [Blinue/Magpie#969]
### Magpie version 程序版本

0.11.1

### Windows version 系统版本

win10 22H2

### Related screenshot (optional) 相关截图（可选）

https://github.com/user-attachments/assets/8ed8bf02-f385-438b-b6f6-31ea053c3da2

### Reproduction steps 复现步骤

Have the game in fullscreen using magpie, and use an overlay window, for example [JL](https://github.com/rampaa/JL) or windows built-in [On-Screen Keyboard](https://support.microsoft.com/en-us/windows/use-the-on-screen-keyboard-osk-to-type-ecbb5e08-5b4e-d8c8-f794-81dbf896267a).
Then mouse over the overlay, sometimes the cursor will be seen for a single frame on the other monitor, or sometimes it will jump there completely and you will have to move it back to your main monitor manually.
I've attached a video showing the effect (ignore the double cursor, it's just my recording software) of the mouse completely jumping to the other monitor when simply hovering JL. I've reproduced this with Magpie 0.11.0 and 0.11.1, but it worked correctly in 0.10.6 and other previous versions.

### Log files 日志文件

[magpie.log](https://github.com/user-attachments/files/16269353/magpie.log)

**Comment by Blinue** [comment]
This is likely because the overlay window has a higher integrity level than Magpie, and due to UIPI, the OS prevents Magpie from changing the cursor position. I’ll look into this when I have some free time.

**Comment by HighSoldierr** [comment]
Did you look into this? I have a similar issue when im running an aplication in full screen with magpie and i move my cursor from 1 monitor to an other monitor

**Comment by Blinue** [comment]
This issue should be resolved in v0.11. Try running Magpie as an administrator.

**Comment by HighSoldierr** [comment]
Im running v0.11.1 and even running as an admin, this issue still happens

**Comment by HighSoldierr** [comment]
Here a video example of the issue. Running magpie in admin
https://github.com/user-attachments/assets/7abb8801-36de-4920-920c-9f710591dabb

**Comment by Blinue** [comment]
Are you referring to the cursor automatically skipping over black borders? This is intended behavior: if there’s no screen beyond the black border, the cursor will stop at it; otherwise, it will skip over.

**Comment by HighSoldierr** [comment]
This is not what iam refering to. Im quikly moving my cursor between my 2 monitors to trigger it. Please watch at 0:05 where it first happens. The cursor jumps quikly all the way left to my left monitor. This happens 3 times total in this video.

**Comment by HighSoldierr** [comment]
Hopefully this video makes it more clear

https://github.com/user-attachments/assets/46a4037e-72ad-47d5-9710-8b50eea1bc4b

**Comment by Blinue** [comment]
Thank you for the video; it clearly demonstrates the issue. I’m using Win11 23H2 and haven’t encountered this error, but I’ll investigate further.

**Comment by kanjieater** [comment]
I have also been encountering the same behavior on Win 11 22H2.  I have two vertical monitors and then a horizontal one on the right. The horizontal one is where i use magpie w/ VN's, and it jumps two monitors over when it enters the horizontal duplicate display magpie screen

**Comment by Throgolin** [comment]
Same issue on Windows 10 22H2, exactly as demonstrated in the video. I'd revert to an older version but unfortunately (as far as I'm aware) CuNNy is not available on older builds. 

I use two horizontal monitors, one 1920x1080 60fps and the other 2560x1440 165fps. Scaling the cursor the same as the window and adjusting cursor speed seemed to help reduce the bug, but it still happens. It happens most frequently close to the border between the two monitors and when the cursor is moving particularly fast. In my case, it jumps to the left side of the left monitor (the 1080p one). Wish this could be adressed as it's particularly annoying when mining visual novels and I need to move the cursor between the two windows very often.
